### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by williamcotton** [nkbt/react-copy-to-clipboard#10]

**Comment by nkbt** [comment]
I will do it asap.

**Comment by nkbt** [comment]
I published fresh version to Bower, working example with React 0.14 is at http://codepen.io/nkbt/pen/eNPoQv

It supports both 0.13 and 0.14

NPM package also supports both as peer-dependencies, so it should work whatever React version you use in your project.

**Comment by williamcotton** [comment]
:+1:
