### ISSUE TITLE
Add prop to prevent click from bubbling up/stopPropagation

### ISSUE THREAD

**Issue by tendermario** [nkbt/react-copy-to-clipboard#102]
Hello!

This component is great. However, I have recently wanted to nest it within a table row that on click will navigate to another page, which I do not want when clicking on the cell containing this component. What I propose is a stopPropagation boolean key on this component that would stop the click event from bubbling any further.

I've tried my hand at modifying the code myself to get this to work, something along the lines of:

```
if (stopPropagation) {
  event.stopPropagation();
}
```

in the onClick function, however that doesn't seem to work. Hopefully this can get added in at some point, it seems useful.

**Comment by nkbt** [comment]
But you can totally do `<Copy onClick={e => e.stopPropagation()} .../>`. I am 100% sure it is not `react-copy-to-clipboard` concern.

**Comment by nkbt** [comment]
On a side note, the thing with event bubbling is that you can stop propagation on any level.
Even `<div onClick={e => e.stopPropagation()}><Copy ... /></div>` would do perfectly well.

**Comment by nkbt** [comment]
Probably related to how react passes events, so when it leaves component boundary it is no longer synchronous (or for some other reason), so stopPropagation does not work anymore. So yeah, catching and preventing event up the tree seems like the way to go
