### ISSUE TITLE
npm install build fail

### ISSUE THREAD

**Issue by airicyu** [nkbt/react-copy-to-clipboard#103]
I have a module including react-copy-to-clipboard module, and when running npm install it would fail with below message:

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:4873/react-copy-to-clipboard failed, reason: connect ECONNREFUSED 127.0.0.1:4873

I guess that when the module is building, it would assume localhost webpack-dev-server is started. And when my local is not running webpack-dev-server, the build would be failed.

**Comment by nkbt** [comment]
It does not do any build. And especially any http requests. Check your settings/npm/system it might be a malware

**Comment by airicyu** [comment]
Thanks for your help! Let me have a check with my code first.

**Comment by airicyu** [comment]
Thanks for your help! Let me have a check with my code first.
