### ISSUE TITLE
Does not seem to work with TypeScript

### ISSUE THREAD

**Issue by ChristopherHButler** [nkbt/react-copy-to-clipboard#105]
I am trying to use this library with a React TypeScript project and it does not seem to work. Here is my code: 

`import { CopyToClipboard } from 'react-copy-to-clipboard';`

then inside the render method: 

`<CopyToClipboard text={this.state.shareableLink} >
                        <Button className='ms-welcome__action' buttonType={ButtonType.hero} iconProps={{ iconName: 'ChevronRight' }} onClick={this.copyLinkToClipboard}>Copy To Clipboard</Button>
                    </CopyToClipboard>`

the error I get is: 

[ts] Module '"/Users/.../node_modules/@types/react-copy-to-clipboard/index"' has no exported member 'CopyToClipboard'. [2305]

but the library is in node_modules/react-copy-to-clipboard. I have tried also installing @types/react-copy-to-clipboard but it does not seem to work either. I get the following error: 

[ts] Module '".../node_modules/@types/react-copy-to-clipboard"' has no exported member 'CopyToClipboard'. [2305]

Is there something I am doing wrong or is this a bug with the library?

**Comment by nkbt** [comment]
This is issue of @types/react-copy-to-clipboard. Someone wrote it and it was not me. I do not work with and cannot support TS myself

**Comment by dajomu** [comment]
For anyone else who has found this as a seeming dead end, try this -
`import CopyToClipboard from 'react-copy-to-clipboard';`
instead of - 
`import {CopyToClipboard} from 'react-copy-to-clipboard';`
worked for me as of 5.0.2, types version 4.3.0

**Comment by aeksco** [comment]
I had this same problem under some more specific circumstances - I'm using TypeScript to build a component library, which I then compile + publish as an NPM package.

Was hitting a problem where regardless of import approach, the `CopyToClipboard` component _just_ would crash my app when work when I imported a component from my library that used it.

Ended up being a bit of a show-stopper so I just ended up re-implementing it in a few lines of TypeScript - faster that spending another hour trying to get this working with my setup:

```tsx
import * as React from "react";
import copy from "copy-to-clipboard";

// // // //

export function CopyToClipboard(props: {
    text: string;
    children: (childProps: { copyToClipboard: () => void }) => React.ReactNode;
    onCopy: (onCopyProps: { text: string; copied: boolean }) => void;
    options?: {
        debug?: boolean;
        message?: string;
        format?: string;
    };
}) {
    // Defines copyToClipboard function passed to props.children
    function copyToClipboard() {
        // Copy props.text to clipboard
        const result: boolean = copy(props.text, props.options);

        // Invokes props.onCopy callback
        props.onCopy({ text: props.text, copied: result });
    }

    return (
        <React.Fragment>{props.children({ copyToClipboard })}</React.Fragment>
    );
}
```  

I know re-implementing the package isn't _really_ a "solution", but it unblocked my problem and I was able to continue working - thanks again to @nkbt for this awesome package!
