### ISSUE TITLE
Uncaught TypeError: reselectPrevious is not a function

### ISSUE THREAD

**Issue by kanglang** [nkbt/react-copy-to-clipboard#106]
Can you answer me about this defect?

**Comment by nkbt** [comment]
Nah not really. Not enough information to say anything about it yet.

**Comment by trent-boyd** [comment]
This is usually a problem we've had when running Jest tests. It's an internal method of the underlying `copy-to-clipboard` dependency. If that's the same problem you have, we fixed it with a manual mock, since we don't need to test the internals of it.

Create this file:

``` js
const copy = jest.fn()
export default copy
```

Name it `copy-to-clipboard.js` and put it in here:

```
root
  __mocks__
    copy-to-clipboard.js
```

I hope that solves any issues!

**Comment by jimmybrawn** [comment]
How could we mock `document.execCommand("copy")` ?

**Comment by CosmaTrix** [comment]
I had the same issue with `Jest` and `Testing Library`. I solved that by mocking the `copy-to-clipboard` module.
```typescript
jest.mock('copy-to-clipboard', () => {
  return jest.fn();
});
```

**Comment by safeimuslim** [comment]
@jimmybrawn 
Object.defineProperty(document, 'execCommand', { value: jest.fn() });

**Comment by NeelDsouza** [comment]
@trent-boyd I'm using mocha and I'm getting the same error. How can i do that in mocha? Can u plz guide.

**Comment by trent-boyd** [comment]
> @trent-boyd I'm using mocha and I'm getting the same error. How can i do that in mocha? Can u plz guide.

I haven't used Mocha in a long time, but I don't think it has stubbing or mocking built in. You'd need to use Sinon for that.

https://sinonjs.org/releases/latest/stubs/

**Comment by NeelDsouza** [comment]
@trent-boyd How can i do that in Sinon? I'm bit new to testing and struggling to get out of this error since yesterday.
