### ISSUE TITLE
Getting 404 on server compile - CopyToClipboard.js.map not found

### ISSUE THREAD

**Issue by tedlin182** [nkbt/react-copy-to-clipboard#11]
I get this error in my logs:
```
 { [Error: Url '/public/js/CopyToClipboard.js.map' does not match any routes]
     statusCode: 404,
     message: 'Url \'/public/js/CopyToClipboard.js.map\' does not match any routes' } }
```
I'm using the NPM module of this and Webpack for module bundling.

**Comment by nkbt** [comment]
Could you please paste your webpack config? Thank you

**Comment by nkbt** [comment]
Ping @tedlin182 is this still relevant? Shall I close the ticket?

**Comment by tedlin182** [comment]
Hey @nkbt I think you can close this...we seem to be all good on our end now. Thanks!

**Comment by nkbt** [comment]
Cheers :+1:
