### ISSUE TITLE
How can we add setInterval timer to hide red "copied" text after 2sec?

### ISSUE THREAD

**Issue by Alidhuniya** [nkbt/react-copy-to-clipboard#112]
I want to change the text "click to copy" to "copied".And I can achieve this with this npm but at the same time, I want to hide the "copied" text after 2sec.
below is the sample code

`<Fragment>
      <div className={style.container} id="blue">
        <CopyToClipboard text="#3498DB">
          <div id={style.blue1} className={style.btn}>
            <span className={`${style.gap} ${style.clr}`}>
              <input
              
                type="button"
                
               
                className={style.mybuttonoverlap}
                value="Click to Copy"
              />
              #3498DB
            </span>
          </div>
        </CopyToClipboard>
</Fragment>`

**Comment by nkbt** [comment]
You will need to use some sort of a state, which will flip after a timeout, and remove that text then.
Here is a solution, but since I have not actually run or tested it it would probably need some adjustments.

```jsx
const MyComponent = () => {
  const [hidden, setHidden] = useState(false);
  useEffect(() => {
    const t = hidden ? setTimeout(() => setHidden(true), 2000) : null;
    return () => clearTimeout(t);
  }, [hidden, setHidden]);
  const onCopy = useCallback(() => setHidden(false), [setHidden]);

  return (
    <>
      <CopyToClipboard onCopy={onCopy} />
      {hidden ? null : 'Copied! This text will disappear in 2 sec'}
    </>
  );
};
```


Closing the ticket as it is not related to the library, but just a general React question.
