### ISSUE TITLE
Expose `copy-to-clipboard` functions

### ISSUE THREAD

**Issue by jalalazimi** [nkbt/react-copy-to-clipboard#115]
I need to copy a string inside a function after doing some processes, so using component doesn't mean. I need function instead of the component so I have to install  `copy-to-clipboard` alongside the `react-copy-to-clipboard`. While it's available in the library. The best idea is to expose `copy-to-clipboard` functions.

**Comment by nkbt** [comment]
Please use `copy-to-clipboard` library directly, you really do not need `react-copy-to-clipboard` then
