### ISSUE TITLE
Newlines seem to be stripped from copied text

### ISSUE THREAD

**Issue by jbbarth** [nkbt/react-copy-to-clipboard#12]
Maybe I did something wrong, but if I try to use the component on data with newlines, I get a flat string with everything concatenated on one line in the clipboard. I reproduce this behavior on your codepen demo by just changing the "input" to be a "textarea".

Do you think it is expected behavior? Fixable? If so, how can I help?

**Comment by jbbarth** [comment]
Forget that, I didn't look at the source. It's obvious that the problem is not on "your" side, I'll try to dig into the copy-to-clipboard module. Sorry for the noise.

**Comment by nkbt** [comment]
No worries!
