### ISSUE TITLE
Update code sample

### ISSUE THREAD

**Issue by stelone** [nkbt/react-copy-to-clipboard#126]
All code sample as this : 
`import {CopyToClipboard} from 'react-copy-to-clipboard';` 

instead of 
`import CopyToClipboard from 'react-copy-to-clipboard';` 

it's on github and npm.

**Comment by nkbt** [comment]
Both work fine.

**Comment by stelone** [comment]
Okay didn't know that. 
In @types/react-copy-to-clipboard there is only the second one. 

So with typescript only the second one work.

**Comment by nkbt** [comment]
I don’t use typescript and do not support that package. I suggest opening an issue there

**Comment by stelone** [comment]
okay thanks I will do that.
