### ISSUE TITLE
Does not support Typescript

### ISSUE THREAD

**Issue by froliceric0914** [nkbt/react-copy-to-clipboard#127]
Module '"/node_modules/@types/react-copy-to-clipboard"' has no exported member 'CopyToClipboard'.
 Seemingly this package does not support @ts yet

**Comment by nkbt** [comment]
I am not using TS and I not the author of `@types/react-copy-to-clipboard` type declarations - it is a completely independent package. 

See https://github.com/nkbt/react-copy-to-clipboard/issues/105 for solution
