### ISSUE TITLE
React.StrictMode: `findDomNode` is deprecated

### ISSUE THREAD

**Issue by mimecuvalo** [nkbt/react-copy-to-clipboard#135]
Hello!
A heads up that this warning is currently in this package:
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of CopyToClipboard which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

(here's another package, if it's helpful, and how they did the upgrade: https://github.com/twobin/react-lazyload/pull/292 )

Cheers!

**Comment by nkbt** [comment]
You probably using some library or app code that has `findDOMNode(<CopyToClipboard>)` or something like that. This error you pasted is not about CopyToClipboard, but something that uses it.

CopyToClipboard does not use findDOMNode

**Comment by mimecuvalo** [comment]
Ah, apologies! Sorry about that - you're right.
