### ISSUE TITLE
Unable to use \r \n

### ISSUE THREAD

**Issue by phil3903** [nkbt/react-copy-to-clipboard#15]
My copy needs to respect new lines and returns. Is there support for this?

**Comment by nkbt** [comment]
Hm that's interesting. Are you copying from textarea or something else?

**Comment by nkbt** [comment]
Feel like https://github.com/sudodoki/copy-to-clipboard/issues/14 can fix it.

**Comment by phil3903** [comment]
Yeah I attempted this by using a .replace() on my string, replacing commas with either \n or \r, before I give the string to the copy component. The string console logs properly (with actual returns) before I attempt the copy, but the \r and \n are removed upon copy. This is being done directly in the javascript, not in a textarea.

I'll check out copy-to-clipboard#14.

**Comment by sudodoki** [comment]
Probably, update of copy-to-clipboard dep will fix it.

**Comment by phil3903** [comment]
This is true. Just tried using copy-to-clipboard 2.0.0 by itself. \r and \n are properly supported.

**Comment by nkbt** [comment]
published `4.0.2`
