### ISSUE TITLE
Change 'text' propType to allow functions.

### ISSUE THREAD

**Issue by rgfoley** [nkbt/react-copy-to-clipboard#17]
This is as much a question as it is a request. I was hoping you could let me know your thoughts on allowing functions for the 'text' prop (maybe add another prop, like getText) so that the text doesn't have to be passed on every render, only when the button is clicked.

My use case for this is with Facebook's fixed-data-table, where I am providing a button to copy the table to the clipboard, which first has to get all of the data (fixed-data-table only renders the currently visible rows) and convert it to an html table structure or a csv structure. 

The problem with this is, in most instances of the parent re-rendering, that adds up to a lot of wasted work re-generating the text prop every time. It would be more efficient (at least I think so) to simply pass a function which returns the text to be copied. That way, the text will only be generated when the user actually needs it. It could also open the door for Promise related stuff I guess, but that isn't really relevant here.

I'm kind of a noob, so let me know if this request is completely misguided/already possible.

Thanks.

**Comment by nkbt** [comment]
Hi, @rgfoley 
I reckon for your case it would be better to use directly `copy-to-clipboard`.

See the source of ReactCopyToClipboard - https://github.com/nkbt/react-copy-to-clipboard/blob/master/src/CopyToClipboard.js

It is pretty much simple wrapper over `copyToClipboard` function. You can just render your own button, and on click - use `copyToClipboard` function directly (after serializing all the data). No need to use this component, really... I guess it is not suitable =).
