### ISSUE TITLE
react-copy-to-clipboard don't works on React 18

### ISSUE THREAD

**Issue by Alejandro1709** [nkbt/react-copy-to-clipboard#176]

**Comment by nkbt** [comment]
Any details? Screenshot? Log?

**Comment by Alejandro1709** [comment]
<img width="628" alt="Screen Shot 2022-04-03 at 19 12 44" src="https://user-images.githubusercontent.com/64037397/161455237-a017e37f-94c9-4c53-8649-c74657d3e2cd.png">

**Comment by nkbt** [comment]
Right. So it needs peer dependency update, I see.

**Comment by Alejandro1709** [comment]
Thank You!

**Comment by jackyleehong** [comment]
Any update on this issue?

**Comment by RaxoCoding** [comment]
Same issue here

**Comment by nkbt** [comment]
https://github.com/nkbt/react-copy-to-clipboard/pull/177 going to publish new minor version soon (don't see any breaking changes, should be safe to update soon)

**Comment by nkbt** [comment]
Published react-copy-to-clipboard@5.1.0

<img width="782" alt="image" src="https://user-images.githubusercontent.com/175264/163186038-0c873c2c-8110-4bd7-98d0-1d5d826be9e3.png">
