### ISSUE TITLE
Please add a Changelog.md or a changelog to all release tags

### ISSUE THREAD

**Issue by natterstefan** [nkbt/react-copy-to-clipboard#178]
Hi @nkbt,

first of all, thanks for the package. I appreciate your work and effort. One question and request though, can you add a changelog to all release tags consistently, please?

This helps keep an eye on (breaking) changes you released and new features. That would be very helpful when one decides to upgrade your package or not. Comparing tags ourselves takes too much time.

Thank you very much.

**Comment by nkbt** [comment]
I do maintain changelog in releases section of github repo itself. But as this process is manual may miss one or two updates

**Comment by nkbt** [comment]
Here https://github.com/nkbt/react-copy-to-clipboard/releases

**Comment by natterstefan** [comment]
> I do maintain changelog in releases section of github repo itself. But as this process is manual may miss one or two updates

No worries, I understand that this can happen. Especially when the process is manual and not automated.

But I can't see a changelog for `v5.1.0` (yet). 🤔

![image](https://user-images.githubusercontent.com/1043668/164640287-14809ff6-8755-425a-8389-b0854019324d.png)

Can you please add it?

**Comment by nkbt** [comment]
Yeah I have just released it and forgot to update release page. It only adds react 18 peer dependency (plus internal dev deps updates that should not have any effect on public api)

**Comment by natterstefan** [comment]
Thank you, @nkbt. I appreciate it.

**Comment by nkbt** [comment]
Updated
https://github.com/nkbt/react-copy-to-clipboard/releases/tag/v5.1.0
