### ISSUE TITLE
.yarn folder is added in the v5.1.0 release

### ISSUE THREAD

**Issue by olegabr** [nkbt/react-copy-to-clipboard#179]
Is it intentional?

**Comment by nkbt** [comment]
Certainly not, thanks for letting know. That's very much unintentional.

**Comment by nkbt** [comment]
`.yarn` is not part of packaged release.

https://unpkg.com/browse/react-copy-to-clipboard@5.1.0/

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/175264/167556919-ee978004-480f-40a7-a016-f7c71815c0ae.png">


Closing as not an issue.
