### ISSUE TITLE
Type error: 'CopyToClipboard' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by bookyo** [nkbt/react-copy-to-clipboard#180]
```
./pages/disk/[id].tsx:163:14
Type error: 'CopyToClipboard' cannot be used as a JSX component.
  Its instance type 'CopyToClipboard' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("D:/www/cloud-disk/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props

  161 |             <input type='text' readOnly value={config.domain + '/s/' + shareId + ' ，code：' + code} className="input input-bordered w-full">
  162 |             </input>
> 163 |             <CopyToClipboard text={config.domain + '/s/' + shareId + '，code：' + code} onCopy={(e) => toast.success('success', { duration: 3000 })}>
      |              ^
  164 |               <button className="btn btn-square">copy
  165 |               </button>
  166 |             </CopyToClipboard>
```

```
"dependencies": {
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/typography": "^0.5.2",
    "@types/react-dom": "18",
    "axios": "^0.26.1",
    "daisyui": "^2.13.6",
    "dayjs": "^1.11.2",
    "filepond": "^4.30.3",
    "filepond-plugin-file-validate-type": "^1.2.6",
    "hls.js": "^1.1.5",
    "next": "latest",
    "next-auth": "^4.3.1",
    "react": "18",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dom": "18",
    "react-filepond": "^7.1.1",
    "react-hot-toast": "^2.2.0",
    "tus-js-client": "^2.3.1"
  },
  "devDependencies": {
    "@types/node": "17.0.4",
    "@types/react": "18",
    "@types/react-copy-to-clipboard": "5.0.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1",
    "prettier-plugin-tailwindcss": "^0.1.1",
    "tailwindcss": "^3.0.7",
    "typescript": "4.5.4"
  }
```

somebody help me?

**Comment by nkbt** [comment]
I am not supporting `@types/react-copy-to-clipboard`. I am not a TypeSctipt developer.

**Comment by thinnakrit** [comment]
Create new file for use typescript
and change ```React.ReactNode``` to ```React.ReactChild```

CopyToClipboardTypes.ts
```
import * as React from 'react';

export as namespace CopyToClipboard;

declare class CopyToClipboard extends React.PureComponent<CopyToClipboard.Props> {}

declare namespace CopyToClipboard {
    class CopyToClipboard extends React.PureComponent<Props> {}

    interface Options {
        debug?: boolean | undefined;
        message?: string | undefined;
        format?: string | undefined; // MIME type
    }

    interface Props {
        children?: React.ReactChild;
        text: string;
        onCopy?(text: string, result: boolean): void;
        options?: Options | undefined;
    }
}

export = CopyToClipboard;
```

**Comment by benomatis** [comment]
@thinnakrit isn't the file name supposed to be `CopyToClipboardTypes.d.ts` (noteice the `d` before the `ts` extension - ie. a declaration file)...?

**Comment by getellez** [comment]
was this solved in the new version 5.1.0?

**Comment by nkbt** [comment]
`@types/react-copy-to-clipboard` is not my package, it is not me who wrote it and I am not supporting it. Whoever wrote it made a mistake and it needs to be fixed. There is no issue importing component when correct types are used.

**Comment by thinnakrit** [comment]
> Create new file for use typescript and change `React.ReactNode` to `React.ReactChild`
> 
> CopyToClipboardTypes.ts
> 
> ```
> import * as React from 'react';
> 
> export as namespace CopyToClipboard;
> 
> declare class CopyToClipboard extends React.PureComponent<CopyToClipboard.Props> {}
> 
> declare namespace CopyToClipboard {
>     class CopyToClipboard extends React.PureComponent<Props> {}
> 
>     interface Options {
>         debug?: boolean | undefined;
>         message?: string | undefined;
>         format?: string | undefined; // MIME type
>     }
> 
>     interface Props {
>         children?: React.ReactChild;
>         text: string;
>         onCopy?(text: string, result: boolean): void;
>         options?: Options | undefined;
>     }
> }
> 
> export = CopyToClipboard;
> ```

Can get my code fixed in this repo?

**Comment by thinnakrit** [comment]
> 

But it probably won't be possible since this repo isn't Typescript.

**Comment by thinnakrit** [comment]
> 

Can i help you to compiled you code to Typescript ?

**Comment by nkbt** [comment]
I don't want to support typescript in this repo. Please update `@types/react-copy-to-clipboard` package instead.

**Comment by benomatis** [comment]
@nkbt so why don't you close this issue then...?
