### ISSUE TITLE
'@types/react-copy-to-clipboard@^5.0.3' tarball not found

### ISSUE THREAD

**Issue by leopinzon** [nkbt/react-copy-to-clipboard#185]
Hey guys, I'm getting the following errors when trying to install the v. ^5.0.2 (aka. 5.0.3)::

```6:08:10 PM: npm ERR! code E404
6:08:10 PM: npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/react-copy-to-clipboard/-/react-copy-to-clipboard-5.0.3.tgz
6:08:10 PM: npm ERR! 404
6:08:10 PM: npm ERR! 404  '@types/react-copy-to-clipboard@^5.0.2' is not in the npm registry.
6:08:10 PM: npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
6:08:10 PM: npm ERR! 404 It was specified as a dependency of 'repo'
6:08:10 PM: npm ERR! 404
6:08:10 PM: npm ERR! 404 Note that you can also install from a
6:08:10 PM: npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by nkbt** [comment]
1. Types are not supported by the author
2.  seems like those versions never were published (or there is some network error)

either way there is nothing I can help with

**Comment by wisdomosara** [comment]
i've been having this issue for over 6 hours now.. yarn install always fails at this point with this same error

**Comment by nkbt** [comment]
I do not support type declaration package. No idea why it tries to download non existent file

**Comment by wisdomosara** [comment]
Okay..

**Comment by wisdomosara** [comment]
Thanks

**Comment by leopinzon** [comment]
@nkbt look at this::
https://registry.npmjs.org/@types/react-copy-to-clipboard/

**Comment by nkbt** [comment]
@leopinzon looks like types automated publish glitched after my lib was published. Nothing to do with the library though. I have no idea how to fix it except trying to publish new version.

**Comment by leopinzon** [comment]
Got it, thank you!

**Comment by nkbt** [comment]
Looks like it has been republished and now is available

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/175264/176983948-2bd79e48-61c2-48c8-ad70-e2660dbc57bf.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/175264/176983964-4e01e4e9-a62f-4a3e-bb80-8a8437778ca4.png">
