### ISSUE TITLE
Get values asynchronously when clicking copy

### ISSUE THREAD

**Issue by tongtongde** [nkbt/react-copy-to-clipboard#186]
When you click Copy, you get the value asynchronously, and then you can't get the latest value
`const onClick= () => {
    setCopyText('text');
  };
<CopyToClipboard
            text={copyText}
          >
            <Typography.Link>
              <ShareAltOutlined onClick={onClick} />
            </Typography.Link>
          </CopyToClipboard>`
consider exposing the copy method？

**Comment by nkbt** [comment]
Why would you need react-copy-to-clipboard then? Just use copy-to-clipboard lib directly
