### ISSUE TITLE
Copy not working on custom component

### ISSUE THREAD

**Issue by ErikParso** [nkbt/react-copy-to-clipboard#188]
Custom component cannot be used as child on CopyToclipboard. I had to wrap it in div or span
![image](https://user-images.githubusercontent.com/35962203/190242206-f2d7dc4c-c566-4d46-8b18-226de38c3cc9.png)

**Comment by nkbt** [comment]
I have updated Codepen with a case using custom component MyButton. And it does work just fine.

https://codepen.io/nkbt/pen/eNPoQv?editors=0011

There is no issue using custom component

**Comment by ErikParso** [comment]
I see I must pass props to the component. Thanks.

**Comment by mdbaniani** [comment]
> https://codepen.io/nkbt/pen/eNPoQv?editors=0011

How would you modify your code in order to work then?

**Comment by mdbaniani** [comment]
> Custom component cannot be used as child on CopyToclipboard. I had to wrap it in div or span ![image](https://user-images.githubusercontent.com/35962203/190242206-f2d7dc4c-c566-4d46-8b18-226de38c3cc9.png)

How would you modify your code in order to work then?
