### ISSUE TITLE
Feature request: Typescript support

### ISSUE THREAD

**Issue by ThaJay** [nkbt/react-copy-to-clipboard#196]
As seen in various issues and pull requests, there is a demand for supporting typescript from the library instead of relying on a `@types` repo.

Perhaps the types from `@types/react-copy-to-clipboard` could just be added to this project?

Some sort of fix supported by the developers of this package would be nice, as this seems to be by far the most popular react clipboard package at the moment.

**Comment by nkbt** [comment]
I do not want to support TS myself.
`@types/react-copy-to-clipboard` exists specifically for that reason and not supported by me.
