### ISSUE TITLE
children proptype is too restrictive

### ISSUE THREAD

**Issue by danteoh** [nkbt/react-copy-to-clipboard#21]
You should loosen the children proptype requirement since children can be an array.

eg,

```
<CopyToClipboard text={"some text}>
  <span>Copy to Clipboard</span>
  <i className='fa fa-clipboard' />
</CopyToClipboard>
```

**Comment by nkbt** [comment]
Unfortunately not, since we clone children and define `onClick` ont the only child passed. ReactCopyToClipboard does not add any extra dom elements, so it cannot accept multiple children.
