### ISSUE TITLE
copy doesn't work when -webkit-user-select is set to none

### ISSUE THREAD

**Issue by PierBover** [nkbt/react-copy-to-clipboard#24]
Copy doesn't work when using `-webkit-user-select: none;`.

It works when using `user-select: none;`, but that CSS property is not supported on any browser yet.

**Comment by nkbt** [comment]
I guess it should not really, since copying is done using selection. When selection is disabled, no copying is possible

**Comment by PierBover** [comment]
Makes sense.

Solved it by adding `-webkit-user-select: auto;` to the click element.

**Comment by nkbt** [comment]
:ok_hand:

**Comment by sudodoki** [comment]
@PierBover are you setting `-webkit-user-select: none;` on body element?

**Comment by PierBover** [comment]
@sudodoki yes.
