### ISSUE TITLE
Support for React 0.14

### ISSUE THREAD

**Issue by moroshko** [nkbt/react-copy-to-clipboard#3]
Looks like `react-copy-to-clipboard` does not support React 0.14.0-beta3 yet:

> npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-copy-to-clipboard@1.0.3 wants react@^0.13.3

Any chance to add support for 0.14.0-beta3?

**Comment by nkbt** [comment]
Should be ok, I don't use any 0.13-specific features. I'll check it asap.

**Comment by nkbt** [comment]
Published 1.0.4 version with support of `~react@0.14.0-beta`
Tested with beta3, works perfect.

**Comment by moroshko** [comment]
Thanks a lot!
