### ISSUE TITLE
Getting warnings

### ISSUE THREAD

**Issue by thewebsitedev** [nkbt/react-copy-to-clipboard#50]
Hi there,

Thank you for this wonderful component!

I am getting the below warnings on latest Chrome:
```
127:14  warning  Script URL is a form of eval  no-script-url (webpackHotDevClient.js:181)
133:14  warning  Script URL is a form of eval  no-script-url (webpackHotDevClient.js:181)
139:14  warning  Script URL is a form of eval  no-script-url (webpackHotDevClient.js:181)
```

OS X 10.11.6
Chrome Version 55.0.2883.95 (64-bit)

Edit: I am using 

How to resolve these?

**Comment by nkbt** [comment]
It might be related to your webpack config or how you import the lib and not a library itself.
Never seen this happening before, so without reproducible example - really hard to help...
