### ISSUE TITLE
npm prune removes copy-to-clipboard dependency

### ISSUE THREAD

**Issue by sokki** [nkbt/react-copy-to-clipboard#54]
Since 4.2.3, `copy-to-clipboard` is in both `dependencies` and `devDependencies`. 

When I run `npm prune --production`, `copy-to-clipboard` gets removed. So now, I need to explicit add it to my projects dependencies ...

```
node@6.8.0
npm@4.4.4
```

**Comment by nkbt** [comment]
Yep, `npm prune` is totally broken now after complete rewrite https://github.com/npm/npm/issues/15669

Our best solution so far is:

```sh
docker run -v $(pwd):/app -w /app -it mhart/alpine-node:7.4.0 npm prune --production
```

PS: tho removing `copy-to-clipboard` from dev deps would be a good idea anyway.
