### ISSUE TITLE
Keyboard accessibility?

### ISSUE THREAD

**Issue by callumlocke** [nkbt/react-copy-to-clipboard#57]
When I press the button by tabbing to focus it and pressing <kbd>Space</kbd> or <kbd>Enter</kbd>, it doesn't seem to copy anything.

**Comment by nkbt** [comment]
Cannot reproduce.

![acc](https://cloud.githubusercontent.com/assets/175264/25213499/5e19618a-25d4-11e7-8ba5-e8e3a170c6ed.gif)


^ I hit `Space` and everything works.
