### ISSUE TITLE
it does not support by iOS9 safari?

### ISSUE THREAD

**Issue by bbb324** [nkbt/react-copy-to-clipboard#66]
it does works on iOS 19 safari, but in iOS9 when click it pops out a window, a bad user experience, any idea to fix it ?

**Comment by nkbt** [comment]
If it is not supported - popup is a fallback solution. See https://github.com/sudodoki/copy-to-clipboard/#browser-support notes

I don't think we can do much about it.

**Comment by nkbt** [comment]
I am unable to test this since all my ios devices were v10 and now v11.
