### ISSUE TITLE
can't work in next.js export ?

### ISSUE THREAD

**Issue by vagusX** [nkbt/react-copy-to-clipboard#68]
I used it in a next.js project, it works well under development, but can't work after `next export`

**Comment by nkbt** [comment]
I don't know what next.js is and what 'next export' is.
Really cannot help unless you have a codepen/jsbin example to run

**Comment by vagusX** [comment]
my mistake and I found that the issue isn't related to this component

**Comment by nkbt** [comment]
Cool, thanks!
