### ISSUE TITLE
Getting type and constructor errors

### ISSUE THREAD

**Issue by SelaO** [nkbt/react-copy-to-clipboard#72]
> ERROR in [at-loader] ./node_modules/@types/react-copy-to-clipboard/index.d.ts:26:39
>     TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
> 
> ERROR in [at-loader] ./src/Models/Main/QrCodeCreator.tsx:57:26
>     TS2604: JSX element type 'CopyToClipboard' does not have any construct or call signatures.

Use:

```
import * as CopyToClipboard from 'react-copy-to-clipboard';
...
                        <CopyToClipboard text={registrationLink} } >
                            <RaisedButton label={ClientResources.qrCodeCreation.copyButton} secondary={true} />
                        </CopyToClipboard>
```

I'm on windows. Any ideas why this happens?

**Comment by nkbt** [comment]
No idea 😟

I am not using Typescript
-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by SelaO** [comment]
Who made the types for this?

**Comment by nkbt** [comment]
There are no types for this component as far as I am aware

**Comment by vaske** [comment]
There are types, but yeah I'm getting same error

**Comment by nkbt** [comment]
I reckon you need to open issue in the repo that has those types, because there are no types for this library in this repo.

**Comment by vaske** [comment]
@nkbt you are rightm I fixed types will make a PR for them ;)

**Comment by nkbt** [comment]
Cool, thanks!
