### ISSUE TITLE
new-lines are trimmed when copied in 

### ISSUE THREAD

**Issue by gioragutt** [nkbt/react-copy-to-clipboard#74]
[link to stackblitz](https://stackblitz.com/edit/react-yimfaj?file=index.js)

the output is a text message to be sent in `whatsapp`.

when I copy in my PC, the output contains newlines.
when I copy in my phone, the new-lines are trimmed.

**Comment by nkbt** [comment]
May it be because of some differences between `\n` and `\r\n`? As far as I know newlines should be fine

**Comment by gioragutt** [comment]
How would you suggest testing your code in a mobile environment?

This problem so far has been consistent to all mobile devices

**Comment by nkbt** [comment]
We probably need to add textarea to the example instead of plain input so it is possible to do multiple lines...

**Comment by nkbt** [comment]
Updated codepen https://codepen.io/nkbt/pen/eNPoQv?editors=0010

Just tested on my iphone with ios11 - multiline works fine.

**Comment by nkbt** [comment]
Also updated http://nkbt.github.io/react-copy-to-clipboard/

Works fine too

**Comment by gioragutt** [comment]
@nkbt thanks for the example. I've done a check with your site as well.

What happens basically is that the text is copied, and later pasted into a `whatsapp` group chat input.
This also happens when using your example(comes out as `some text`) without the new-line,

But it does work when I parse it in the textarea in your example, so I guess that might have something to do with `whatsapp`.

Thanks!
