### ISSUE TITLE
Update to latest node engine

### ISSUE THREAD

**Issue by dachinat** [nkbt/react-copy-to-clipboard#90]
When I run `yarn add react-copy-to-clipboard` I'm getting `error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

I think it's time have have this arranged. I'm using Node 10

**Comment by dachinat** [comment]
Yes you're right, so it's some dependency then..

**Comment by nkbt** [comment]
I will update deps asap, thanks for heads up. It might be some dev dependency. I don't think they are installed together with copy-to-clipboard anyway, but still it needs a refresh.

**Comment by dachinat** [comment]
`error upath@1.0.4:` might be a hint

**Comment by dachinat** [comment]
This issue was fixed [https://github.com/anodynos/upath/commit/8c5f4e10376ed1cd4553d9432297d39a34410c69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](https://github.com/anodynos/upath/commit/8c5f4e10376ed1cd4553d9432297d39a34410c69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) here. Sorry for taking your time and thanks for attention.
