### ISSUE TITLE
Support adding onClick listener to the CopyToClipboard component

### ISSUE THREAD

**Issue by gfpacheco** [nkbt/react-copy-to-clipboard#91]
For now I have to add the `onClick` listener to the parent/child component:

```
<span onClick={stopPropagation}>
  <CopyToClipboard text="...">
    <span>copy</span>
  </CopyToClipboard>
</span>
```

```
<CopyToClipboard text="...">
  <span onClick={stopPropagation}>copy</span>
</CopyToClipboard>
```

Both work.

But this doesn't:

```
<CopyToClipboard text="..." onClick={stopPropagation}>
  <span>copy</span>
</CopyToClipboard>
```

**Comment by nkbt** [comment]
https://github.com/nkbt/react-copy-to-clipboard/blob/master/src/Component.js#L40-L43
It passes onClick down to the child if it is in props

**Comment by gfpacheco** [comment]
No it doesn't.

It calls the original `onClick` of its children. But it doesn't call a `onClick` prop sent to itself.

**Comment by nkbt** [comment]
But why does it matter? `CopyToClipboard` is designed to not create any extra elements and simply wrap the only child it gets. So it cannot really have any event handlers on itself. Your second example is intended usage.

I do not see any value in adding `onClick` or any other props to `CopyToClipboard` itself.

**Comment by nkbt** [comment]
It is certainly not intended to accept any props that will be passed to child element.
