### ISSUE TITLE
UC browser compatibility issues

### ISSUE THREAD

**Issue by zhangshuaidan** [nkbt/react-copy-to-clipboard#96]
when I open the url [http://nkbt.github.io/react-copy-to-clipboard](url), with my  phone, In the browser which name is UC browser,In China , this browser called 'UC浏览器', but  when I Clicked the copy Button, the browser show me a Pop-up box，like this.
![_20180909165017](https://user-images.githubusercontent.com/27200655/45262839-57038800-b451-11e8-9e41-e96d664938d4.jpg)

**Why does this happen?**
**How can I solve it?**

**Comment by nkbt** [comment]
It does not support the feature used by copy to clipboard

https://caniuse.com/#feat=document-execcommand

**Comment by zhangshuaidan** [comment]
ok. Thank you.
