### ISSUE TITLE
copy \t doesn't work

### ISSUE THREAD

**Issue by atishoo** [nkbt/react-copy-to-clipboard#98]
it's weird.

\r or \n is good, but \t can not work.

**Comment by nkbt** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/175264/46778683-8cf1a000-cd60-11e8-8153-9fedb99dfe5c.png)


https://codepen.io/nkbt/pen/oaWMEW

**Comment by atishoo** [comment]
but you paste what you copied to txt or excel or somewhere else, \t will change into space 
![2018-10-12 4 40 23](https://user-images.githubusercontent.com/7723403/46858395-d368fc80-ce3d-11e8-93d6-552e51779c08.png)
space is a dot.
tab is an arrow.

paste what you copied to doc , you can see it's a dot.

that is so weird

**Comment by nkbt** [comment]
What I pasted into textarea was definitely a tab not space. I think som of the text editors may treat tab char a bit differently. 

For example I’ve noticed that if I paste preformatted code all my spaces are gone, only new lines remain in some editors.

At this point I’m not sure we can do much about how pasting works in other places. Unless someone may have better idea why  that happens

**Comment by nkbt** [comment]
Maybe need to check if dependency is outdated in published version...

**Comment by GaddMaster** [comment]
Not sure what's going on with everyone else but mine doesn't copy

text = {this.state.link} (some long link, tested/printed in render to be sure)

copies = link

instead of the links value?

**Comment by nkbt** [comment]
@GaddMaster   Not sure what this means, as my chrome under windows copies everything ok. Please, check how you use it in your app.
